<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class GameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data =[
            [
                "name" => "Assassin's Creed II",
                "genre_id" => 1,
                "price" => 99000,
                "discount_percent" => 100,
                "description" => "Experience the story of Basim, a cunning street thief with nightmarish visions, seeking answers and justice as he navigates the bustling streets of ninth-century Baghdad. Through a mysterious, ancient organization known as the Hidden Ones, he will become a deadly Master Assassin and change his fate in ways he never could have imagined.",
                "company" => "Ubisoft",
                "url" => "images/ac2.avif",
                "logo" => "logo/ac2.avif",
                "banner" => "banner/ac2.jpg",
                "release_date" => "2010-03-05",
                "os" => "Windows 10",
                "gpu" => "Nvidia GTX 1050",
                "cpu" => "Intel Core i5-4460",
                "ram" => 4,
                "storage" => 25,
                "directx" => 11,
                "downloads" => 500,
                "rating" => 4.5,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Assassin's Creed Mirage",
                "genre_id" => 1,
                "price" => 579000,
                "discount_percent" => 0,
                "description" => "An epic story of family, vengeance and conspiracy set in the pristine, yet brutal, backdrop of a Renaissance Italy. New low price!",
                "company" => "Ubisoft",
                "url" => "images/acmirage.avif",
                "logo" => "logo/acmirage.webp",
                "banner" => "banner/acmirage.png",
                "release_date" => "2023-10-05",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 960",
                "cpu" => "Intel Core i5-4590",
                "ram" => 16,
                "storage" => 50,
                "directx" => 11,
                "downloads" => 0,
                "rating" => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Assassin's Creed Odyssey",
                "genre_id" => 3,
                "price" => 619000,
                "discount_percent" => 0,
                "description" => "Choose your fate in Assassin's Creed® Odyssey. From outcast to living legend, embark on an odyssey to uncover the secrets of your past and change the fate of Ancient Greece.",
                "company" => "Ubisoft",
                "url" => "images/acodyssey.avif",
                "logo" => "logo/acodyssey.avif",
                "banner" => "banner/acodyssey.avif",
                "release_date" => "2018-10-05",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 970",
                "cpu" => "Intel Core i7-3770",
                "ram" => 8,
                "storage" => 46,
                "directx" => 11,
                "downloads" => 400,
                "rating" => 4.5,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Assassin's Creed Origins",
                "genre_id" => 3,
                "price" => 619000,
                "discount_percent" => 85,
                "description" => "Assassin's Creed® Origins is a new beginning. Experience a new way to fight while exploring the Great Pyramids and hidden tombs across the country of Ancient Egypt. Live emotional and memorable adventures along your journey, and discover the origin story of the Assassin's Brotherhood.",
                "company" => "Ubisoft",
                "url" => "images/acorigins.avif",
                "logo" => "logo/acorigins.avif",
                "banner" => "banner/acorigins.avif",
                "release_date" => "2017-10-05",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 660",
                "cpu" => "Intel Core i5-2400s",
                "ram" => 6,
                "storage" => 46,
                "directx" => 11,
                "downloads" => 400,
                "rating" => 4.7,
                "discount_percent" => 0,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Assassin's Creed Syndicate",
                "genre_id" => 1,
                "price" => 409000,
                "discount_percent" => 0,
                "description" => "London, 1868. In the heart of the Industrial Revolution, lead your underworld organization and grow your influence to fight those who exploit the less privileged in the name of progress.",
                "company" => "Ubisoft",
                "url" => "images/acsyndicate.avif",
                "logo" => "logo/acsyndicate.avif",
                "banner" => "banner/acsyndicate.jpg",
                "release_date" => "2015-10-05",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 760",
                "cpu" => "Intel Core i5-2400s",
                "ram" => 6,
                "storage" => 50,
                "directx" => 11,
                "downloads" => 200,
                "rating" => 4.5,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Assassin's Creed Unity",
                "genre_id" => 1,
                "price" => 409000,
                "discount_percent" => 0,
                "description" => "Assassins Creed Unity tells the story of Arno who embarks upon an extraordinary journey to expose the true powers behind the French Revolution.",
                "company" => "Ubisoft",
                "url" => "images/acunity.avif",
                "logo" => "logo/acunity.avif",
                "banner" => "banner/acunity.jpg",
                "release_date" => "2014-11-11",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 680",
                "cpu" => "Intel Core i5-2500k",
                "ram" => 6,
                "storage" => 50,
                "directx" => 9,
                "downloads" => 200,
                "rating" => 4.5,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Assassin's Creed Valhalla",
                "genre_id" => 1,
                "price" => 619000,
                "discount_percent" => 0,
                "description" => "Become Eivor, a legendary Viking raider on a quest for glory. Explore England's Dark Ages as you raid your enemies, grow your settlement, and build your political power.",
                "company" => "Ubisoft",
                "url" => "images/ACValhalla.avif",
                "logo" => "logo/acvalhalla.avif",
                "banner" => "banner/acvalhalla.avif",
                "release_date" => "2020-11-17",
                "os" => "Windows 10 (64-bit only)",
                "gpu" => "NVIDIA GeForce GTX 960",
                "cpu" => "Intel Core i5-4460",
                "ram" => 8,
                "storage" => 50,
                "directx" => 12,
                "downloads" => 350,
                "rating" => 4.6,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Alan Wake 2",
                "genre_id" => 1,
                "price" => 570500,
                "discount_percent" => 0,
                "description" => "Alan Wake is a psychological action thriller, a unique new take in the world of gaming. The game is set in an idyllic all-American small town and its surroundings in the state of Washington. Alan Wake, the game's protagonist, is a bestselling horror writer, who writes a novel about his darkest nightmares. In the game, those nightmares come true.",
                "company" => "Remedy Entertainment",
                "url" => "images/alanwake2.avif",
                "logo" => "logo/alanwake2.avif",
                "banner" => "banner/alanwake2.jpg",
                "release_date" => "2023-10-17",
                "os" => "Windows 10 (64-bit only)",
                "gpu" => "NVIDIA GeForce GTX 1080",
                "cpu" => "Intel Core i7-4460",
                "ram" => 16,
                "storage" => 50,
                "directx" => 12,
                "downloads" => 0,
                "rating" => 0,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "ARK Survival Evolved",
                "genre_id" => 1,
                "price" => 107999,
                "discount_percent" => 30,
                "description" => "Stranded on the shores of a mysterious island, you must learn to survive. Use your cunning to kill or tame the primeval creatures roaming the land, and encounter other players to survive, dominate... and escape!",
                "company" => "Studio Wildcard",
                "url" => "images/ark.avif",
                "logo" => "logo/ark.avif",
                "banner" => "banner/ark.jpg",
                "release_date" => "2017-08-29",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 670",
                "cpu" => "Intel Core i5-2400",
                "ram" => 8,
                "storage" => 60,
                "directx" => 10,
                "downloads" => 500,
                "rating" => 4.6,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Back 4 Blood",
                "genre_id" => 1,
                "price" => 749000,
                "discount_percent" => 0,
                "description" => "Back 4 Blood is a thrilling cooperative first-person shooter from the creators of the critically acclaimed Left 4 Dead franchise. You are at the center of a war against the Ridden. These once-human hosts of a deadly parasite have turned into terrifying creatures bent on devouring what remains of civilization. With the extinction of humanity on the line, it is up to you and your friends to take the fight to the enemy, eradicate the Ridden, and reclaim the world.",
                "company" => "Turtle Rock Studios",
                "url" => "images/back4blood.avif",
                "logo" => "logo/back4blood.avif",
                "banner" => "banner/back4blood.jpg",
                "release_date" => "2021-10-12",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 1050 Ti",
                "cpu" => "Intel Core i5-8400",
                "ram" => 8,
                "storage" => 40,
                "directx" => 11,
                "downloads" => 100,
                "rating" => 4.2,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Cyberpunk 2077",
                "genre_id" => 1,
                "price" => 706000,
                "discount_percent" => 50,
                "description" => "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
                "company" => "CD PROJEKT RED",
                "url" => "images/cyberpunk2077.avif",
                "logo" => "logo/cyberpunk2077.avif",
                "banner" => "banner/cyberpunk2077.jpg",
                "release_date" => "2020-12-10",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 780",
                "cpu" => "Intel Core i5-3570K",
                "ram" => 8,
                "storage" => 70,
                "directx" => 12,
                "downloads" => 500,
                "rating" => 4.1,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "The Cycle: Frontier",
                "genre_id" => 2,
                "price" => 0,
                "discount_percent" => 0,
                "description" => "The Cycle is a free-to-play, multiplayer FPS with a unique mix of PvP & PvE. You are a Prospector on the edge of space in pursuit of fame & fortune. Outsmart your enemies to finish the most contracts & escape before The Cycle, a deadly storm, hits you!",
                "company" => "YAGER Development",
                "url" => "images/cyclefrontier.webp",
                "logo" => "logo/cyclefrontier.avif",
                "banner" => "banner/cyclefrontier.jpg",
                "release_date" => "2024-08-06",
                "os" => "Windows 10 64-Bit",
                "gpu" => "NVIDIA GeForce GTX 760",
                "cpu" => "Intel® Core™ i5-4590",
                "ram" => 6,
                "storage" => 37,
                "directx" => 11,
                "downloads" => 0,
                "rating" => 0,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Dead by Daylight",
                "genre_id" => 5,
                "price" => 134999,
                "discount_percent" => 0,
                "description" => "Dead by Daylight is a multiplayer (4vs1) horror game where one player takes on the role of the savage Killer, and the other four players play as Survivors, trying to escape the Killer and avoid being caught and killed.",
                "company" => "Behaviour Interactive",
                "url" => "images/DeadByDaylight.avif",
                "logo" => "logo/DeadByDaylight.avif",
                "banner" => "banner/DeadByDaylight.avif",
                "release_date" => "2016-06-14",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 460",
                "cpu" => "Intel Core i3-4170",
                "ram" => 8,
                "storage" => 50,
                "directx" => 11,
                "downloads" => 500,
                "rating" => 4.0,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Dead Island 2",
                "genre_id" => 1,
                "price" => 659000,
                "discount_percent" => 0,
                "description" => "A deadly virus is spreading across Los Angeles, turning inhabitants into zombies. Bitten, infected, but more than just immune, uncover the truth behind the outbreak and discover who -or what- you are.",
                "company" => "Deep Silver",
                "url" => "images/DeadIsland2.avif",
                "logo" => "logo/DeadIsland2.avif",
                "banner" => "banner/DeadIsland2.avif",
                "release_date" => "2023-04-21",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 1060 (6144 VRAM)",
                "cpu" => "Intel Core i7-7700HQ",
                "ram" => 10,
                "storage" => 70,
                "directx" => 12,
                "downloads" => 1700,
                "rating" => 4.5,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Destiny 2",
                "genre_id" => 2,
                "price" => 0,
                "discount_percent" => 0,
                "description" => "Dive into the free-to-play world of Destiny 2 to experience responsive first-person shooter combat, explore the mysteries of our solar system, and unleash elemental abilities against powerful enemies. Download today to create your Guardian and collect unique weapons, armor, and gear to customize your look and playstyle. Experience Destiny 2’s cinematic story alone or with friends, join other Guardians for challenging co-op missions, or compete against them in a variety of PvP modes.",
                "company" => "Bungie",
                "url" => "images/destiny2.avif",
                "logo" => "logo/destiny2.webp",
                "banner" => "banner/destiny2.jpg",
                "release_date" => "2017-10-24",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 660",
                "cpu" => "Intel Core i3-3250",
                "ram" => 6,
                "storage" => 105,
                "directx" => 11,
                "downloads" => 500,
                "rating" => 4.3,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Europa Universalis IV",
                "genre_id" => 7,
                "price" => 350999,
                "discount_percent" => 100,
                "description" => "The empire building game Europa Universalis IV gives you control of a nation to guide through the years in order to create a dominant global empire. Rule your nation through the centuries, with unparalleled freedom, depth and historical accuracy. True exploration, trade, warfare and diplomacy will be brought to life in this epic title rife with rich strategic and tactical depth.",
                "company" => "Paradox Development Studio",
                "url" => "images/europa4.avif",
                "logo" => "logo/europa4.avif",
                "banner" => "banner/europa4.jpg",
                "release_date" => "2013-08-13",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 460",
                "cpu" => "Intel Core i3-2100",
                "ram" => 4,
                "storage" => 6,
                "directx" => 9,
                "downloads" => 500,
                "rating" => 4.5,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Fallout New Vegas",
                "genre_id" => 1,
                "price" => 89999,
                "discount_percent" => 0,
                "description" => "Feel the Heat in New Vegas! Not even nuclear fallout could slow the hustle of Sin City. Explore the vast expanses of the desert wastelands and see the Great Southwest as could only be imagined in Fallout.",
                "company" => "Obsidian Entertainment",
                "url" => "images/fallout.avif",
                "logo" => "logo/fallout.avif",
                "banner" => "banner/fallout.avif",
                "release_date" => "2010-10-19",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 650 Ti",
                "cpu" => "Intel Core i5-2300",
                "ram" => 4,
                "storage" => 10,
                "directx" => 9,
                "downloads" => 500,
                "rating" => 4.5,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "For Honor",
                "genre_id" => 1,
                "price" => 309000,
                "discount_percent" => 0,
                "description" => "Enter the chaos of war as a bold Knight, brutal Viking, or deadly Samurai, three of the greatest warriors of legend. Wield your blade like never before with the innovative Art of Battle combat system that puts you in total control of your warrior.",
                "company" => "Ubisoft",
                "url" => "images/forhonor.avif",
                "logo" => "logo/forhonor.avif",
                "banner" => "banner/forhonor.avif",
                "release_date" => "2017-02-14",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 950",
                "cpu" => "Intel Core i3-4150",
                "ram" => 4,
                "storage" => 90,
                "directx" => 11,
                "downloads" => 600,
                "rating" => 4.5,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Fortnite",
                "genre_id" => 14,
                "price" => 0,
                "discount_percent" => 0,
                "description" => "Fortnite is the completely free multiplayer game where you and your friends collaborate to create your dream Fortnite world or battle to be the last one standing. Play both Battle Royale and Fortnite Creative for FREE. Download now and jump into the action.",
                "company" => "Epic Games",
                "url" => "images/fortnite.avif",
                "logo" => "logo/fortnite.webp",
                "banner" => "banner/fortnite.jpg",
                "release_date" => "2017-07-25",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 660",
                "cpu" => "Intel Core i3-3225",
                "ram" => 4,
                "storage" => 100,
                "directx" => 11,
                "downloads" => 2500,
                "rating" => 4.2,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Genshin Impact",
                "genre_id" => 1,
                "price" => 0,
                "discount_percent" => 0,
                "description" => "Step into Teyvat, a vast world teeming with life and flowing with elemental energy. You and your sibling arrived here from another world. Separated by an unknown god, stripped of your powers, and cast into a deep slumber, you now awake to a world very different from when you first arrived.",
                "company" => "miHoYo Limited",
                "url" => "images/genshin.avif",
                "logo" => "logo/genshin.avif",
                "banner" => "banner/genshin.jpg",
                "release_date" => "2020-09-28",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GT 1030",
                "cpu" => "Intel Core i5",
                "ram" => 8,
                "storage" => 30,
                "directx" => 11,
                "downloads" => 1800,
                "rating" => 4.4,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "God of War",
                "genre_id" => 1,
                "price" => 899999,
                "discount_percent" => 0,
                "description" => "His vengeance against the Gods of Olympus years behind him, Kratos now lives as a man in the realm of Norse Gods and monsters. It is in this harsh, unforgiving world that he must fight to survive… and teach his son to do the same.",
                "company" => "Santa Monica Studio",
                "url" => "images/godofwar.avif",
                "logo" => "logo/godofwar.avif",
                "banner" => "banner/godofwar.jpg",
                "release_date" => "2019-10-15",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 970",
                "cpu" => "Intel Core i5-2500K",
                "ram" => 8,
                "storage" => 70,
                "directx" => 11,
                "downloads" => 800,
                "rating" => 4.7,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Grand Theft Auto V",
                "genre_id" => 4,
                "price" => 699000,
                "discount_percent" => 0,
                "description" => "When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled with some of the most frightening and deranged elements of the criminal underworld, the U.S. government and the entertainment industry, they must pull off a series of dangerous heists to survive in a ruthless city in which they can trust nobody, least of all each other.",
                "company" => "Rockstar Games",
                "url" => "images/gtav.avif",
                "logo" => "logo/gtav.avif",
                "banner" => "banner/gtav.jpg",
                "release_date" => "2015-04-14",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 960",
                "cpu" => "Intel Core i5-3470",
                "ram" => 8,
                "storage" => 72,
                "directx" => 11,
                "downloads" => 2250,
                "rating" => 4.8,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "The Crew 2",
                "genre_id" => 9,
                "price" => 515000,
                "discount_percent" => 50,
                "description" => "The newest iteration in the revolutionary franchise, The Crew® 2 captures the thrill of the American motorsports spirit in one of the most exhilarating open worlds ever created. Welcome to Motornation, a huge, varied, action-packed, and beautiful playground built for motorsports throughout the entire US of A. Enjoy unrestrained exploration on ground, sea, and sky. From coast to coast, street and pro racers, off-road explorers, and freestylers gather and compete in all kinds of disciplines. Join them in high-octane contests and share every glorious moment with the world.",
                "company" => "Ivory Tower",
                "url" => "images/crew2.avif",
                "logo" => "logo/crew2.avif",
                "banner" => "banner/crew2.avif",
                "release_date" => "2018-06-29",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 1050 Ti",
                "cpu" => "Intel Core i5-2400s",
                "ram" => 8,
                "storage" => 52,
                "directx" => 11,
                "downloads" => 300,
                "rating" => 4.5,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "HITMAN World of Assassination",
                "genre_id" => 11,
                "price" => 518000,
                "discount_percent" => 0,
                "description" => "Become Agent 47 in the ultimate spy-thriller adventure across more than 20 locations HITMAN World of Assassination brings together the best of HITMAN HITMAN 2 and HITMAN 3 including the main campaign, escalations, elusive target arcades and HITMAN: Freelancer.",
                "company" => "IO Interactive A/S",
                "url" => "images/hitman.avif",
                "logo" => "logo/hitman.webp",
                "banner" => "banner/hitman.jpg",
                "release_date" => "2021-01-20",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 1070",
                "cpu" => "Intel Core i5-2500K",
                "ram" => 8,
                "storage" => 80,
                "directx" => 12,
                "downloads" => 600,
                "rating" => 4.8,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Honkai: Star Rail",
                "genre_id" => 3,
                "price" => 0,
                "discount_percent" => 0,
                "description" => "The greatsword-wielding heroine, Durandal, and Rita Rossweisse, the fallen angel, have joined hands to protect the world from the Honkai menace. Play as Durandal or Rita and venture into the Quantum Sea with the help of the new Quantum-type battlesuit, Starlit Astrologos!",
                "company" => "COGNOSPHERE PTE. LTD",
                "url" => "images/honkai.avif",
                "logo" => "logo/honkai.avif",
                "banner" => "banner/honkai.jpg",
                "release_date" => "2023-04-26",
                "os" => "Windows 7 SP1 64-bit",
                "gpu" => "Nvidia GeForce 8800GT",
                "cpu" => "Intel Core i5-3470",
                "ram" => 8,
                "storage" => 15,
                "directx" => 11,
                "downloads" => 1700,
                "rating" => 4.7,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Horion Zero Dawn",
                "genre_id" => 1,
                "price" => 659000,
                "discount_percent" => 30,
                "description" => "Experience Aloy’s legendary quest to unravel the mysteries of a future Earth ruled by Machines. Use devastating tactical attacks against your prey and explore a majestic open world in this award-winning action RPG!",
                "company" => "Guerrilla",
                "url" => "images/horizonzerodawn.avif",
                "logo" => "logo/horizonzerodawn.avif",
                "banner" => "banner/horizonzerodawn.jpg",
                "release_date" => "2020-08-07",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 1050 Ti",
                "cpu" => "Intel Core i7-7700HQ",
                "ram" => 8,
                "storage" => 100,
                "directx" => 12,
                "downloads" => 900,
                "rating" => 4.9,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "The Lord of the Rings: Return to Moria™",
                "genre_id" => 1,
                "price" => 109000,
                "discount_percent" => 0,
                "description" => "The Lord of the Rings Online™: Return to Moria™ - Digital Download",
                "company" => "Free Range Games",
                "url" => "images/lotr.avif",
                "logo" => "logo/lotr.avif",
                "banner" => "banner/lotr.png",
                "release_date" => "2023-12-31",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 1660",
                "cpu" => "Intel Core i7-7700HQ",
                "ram" => 8,
                "storage" => 80,
                "directx" => 12,
                "downloads" => 0,
                "rating" => 0,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "OCTOPATH TRAVELER™",
                "genre_id" => 3,
                "price" => 570000,
                "discount_percent" => 40,
                "description" => "Eight travelers. Eight adventures. Eight roles to play. Embark on an epic journey across the vast and wondrous world of Orsterra and discover the captivating stories of each of the eight travelers.",
                "company" => "Square Enix",
                "url" => "images/octopath.avif",
                "logo" => "logo/octopath.avif",
                "banner" => "banner/octopath.jpg",
                "release_date" => "2019-06-07",
                "os" => "Windows 7 SP1 / 8.1 / 10 64-bit only",
                "gpu" => "NVIDIA GeForce GTX 750 Ti",
                "cpu" => "Intel Core i3-3210",
                "ram" => 4,
                "storage" => 5,
                "directx" => 11,
                "downloads" => 500,
                "rating" => 4.8,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Paladins",
                "genre_id" => 2,
                "price" => 0,
                "discount_percent" => 0,
                "description" => "Join 30+ million players in Paladins, the free-to-play fantasy team-based shooter sensation. Wield guns and magic as a legendary Champion of the Realm, customizing your core set of abilities to play exactly how you want to play.",
                "company" => "Evil Mojo Games",
                "url" => "images/paladins.avif",
                "logo" => "logo/paladins.avif",
                "banner" => "banner/paladins.avif",
                "release_date" => "2018-05-20",
                "os" => "Windows 10",
                "gpu" => "Nvidia GeForce 8800 GT",
                "cpu" => "Intel Core 2 Duo E4600",
                "ram" => 4,
                "storage" => 30,
                "directx" => 11,
                "downloads" => 200,
                "rating" => 4.1,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Rainbow Six Siege",
                "genre_id" => 2,
                "price" => 216000,
                "discount_percent" => 70,
                "description" => "Squad up and breach in to explosive 5v5 PVP action. Tom Clancy's Rainbow Six® Siege features a huge roster of specialized operators, each with game-changing gadgets to help you lead your team to victory.",
                "company" => "Ubisoft",
                "url" => "images/r6s.avif",
                "logo" => "logo/r6s.webp",
                "banner" => "banner/r6s.avif",
                "release_date" => "2015-12-01",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 460",
                "cpu" => "Intel Core i3 560",
                "ram" => 6,
                "storage" => 61,
                "directx" => 11,
                "downloads" => 500,
                "rating" => 4.4,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Tom Clancy’s Rainbow Six® Extraction",
                "genre_id" => 2,
                "price" => 409000,
                "discount_percent" => 0,
                "description" => "The next mainline installment in the Rainbow Six franchise, Tom Clancy’s Rainbow Six Extraction is a brand-new tactical co-op experience where players will be facing an always-evolving alien threat. Set in the Tom Clancy’s Rainbow Six Siege universe, Rainbow Six Extraction is built on the foundations of one of the best shooters of this generation. ",
                "company" => "Ubisoft",
                "url" => "images/r6se.avif",
                "logo" => "logo/r6se.avif",
                "banner" => "banner/r6se.png",
                "release_date" => "2022-01-20",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 960",
                "cpu" => "Intel Core i5-6600K",
                "ram" => 8,
                "storage" => 60,
                "directx" => 11,
                "downloads" => 350,
                "rating" => 4.8,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "name" => "Red Dead Redemption 2",
                "genre_id" => 4,
                "price" => 659000,
                "discount_percent" => 0,
                "description" => "America, 1899. The end of the wild west era has begun as lawmen hunt down the last remaining outlaw gangs. Those who will not surrender or succumb are killed. After a robbery goes badly wrong in the western town of Blackwater, Arthur Morgan and the Van der Linde gang are forced to flee.",
                "company" => "Rockstar Games",
                "url" => "images/rdr2.avif",
                "logo" => "logo/rdr2.avif",
                "banner" => "banner/rdr2.jpg",
                "release_date" => "2019-11-05",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 1060",
                "cpu" => "Intel Core i5-2500K",
                "ram" => 8,
                "storage" => 150,
                "directx" => 12,
                "downloads" => 1500,
                "rating" => 4.9,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "Remnant II",
                "genre_id" => 1,
                "price" => 529999,
                "discount_percent" => 40,
                "description" => "The Remnant: From the Ashes - Complete Edition includes Remnant: From the Ashes, the official soundtrack, and the Swamps of Corsus and Subject 2923 DLCs.",
                "company" => "Gunfire Games",
                "url" => "images/remnant2.avif",
                "logo" => "logo/remnant2.avif",
                "banner" => "banner/remnant2.avif",
                "release_date" => "2023-07-25",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 970",
                "cpu" => "Intel Core i5-4690K",
                "ram" => 8,
                "storage" => 40,
                "directx" => 11,
                "downloads" => 0,
                "rating" => 4.8,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "Rocket League",
                "genre_id" => 9,
                "price" => 0,
                "discount_percent" => 0,
                "description" => "Rocket League is a high-powered hybrid of arcade-style soccer and vehicular mayhem with easy-to-understand controls and fluid, physics-driven competition. Rocket League includes casual and competitive Online Matches, a fully-featured offline Season Mode, special “Mutators” that let you change the rules entirely, hockey and basketball-inspired Extra Modes, and more than 500 trillion possible cosmetic customization combinations.",
                "company" => "Psyonix LLC",
                "url" => "images/rocketleague.avif",
                "logo" => "logo/rocketleague.webp",
                "banner" => "banner/rocketleague.jpg",
                "release_date" => "2015-07-07",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 260",
                "cpu" => "Intel Core 2 Duo E4600",
                "ram" => 2,
                "storage" => 7,
                "directx" => 9,
                "downloads" => 1800,
                "rating" => 4.5,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "Marvel's Spider-Man Remastered",
                "genre_id" => 1,
                "price" => 879000,
                "discount_percent" => 0,
                "description" => "In Marvel’s Spider-Man Remastered, the worlds of Peter Parker and Spider-Man collide in an original, action-packed story. Play as an experienced Peter Parker, fighting big crime and iconic villains in Marvel’s New York. Web-swing through vibrant neighborhoods and defeat villains with epic takedowns.",
                "company" => "Insomniac Games",
                "url" => "images/spiderman.avif",
                "logo" => "logo/spiderman.avif",
                "banner" => "banner/spiderman.jpg",
                "release_date" => "2020-11-12",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 1060",
                "cpu" => "Intel Core i5-2300",
                "ram" => 8,
                "storage" => 75,
                "directx" => 11,
                "downloads" => 500,
                "rating" => 4.7,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "Marvel’s Spider-Man: Miles Morales",
                "genre_id" => 1,
                "price" => 879000,
                "discount_percent" => 0,
                "description" => "Teenage Miles Morales is adjusting to his new home while following in the footsteps of his mentor, Peter Parker, as a new Spider-Man. When a fierce power struggle threatens to destroy his home, Miles must take up the mantle of Spider-Man and own it.",
                "company" => "Insomniac Games",
                "url" => "images/spidermanmiles.avif",
                "logo" => "logo/spidermanmiles.avif",
                "banner" => "banner/spidermanmiles.jpg",
                "release_date" => "2020-11-18",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 1060",
                "cpu" => "Intel Core i5-2300",
                "ram" => 8,
                "storage" => 75,
                "directx" => 11,
                "downloads" => 1500,
                "rating" => 4.9,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "theHunter: Call of the Wild",
                "genre_id" => 4,
                "price" => 449999,
                "discount_percent" => 60,
                "description" => "Experience the thrill of the hunt in a visually breathtaking, technically groundbreaking, vast open world. Immerse yourself in the atmospheric single player campaign, or share the ultimate hunting experience with friends.",
                "company" => "Expansive Worlds",
                "url" => "images/thehunter.avif",
                "logo" => "logo/thehunter.avif",
                "banner" => "banner/thehunter.avif",
                "release_date" => "2017-02-16",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 660",
                "cpu" => "Intel i3-4170",
                "ram" => 4,
                "storage" => 36,
                "directx" => 12,
                "downloads" => 500,
                "rating" => 4.6,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "Valorant",
                "genre_id" => 2,
                "price" => 0,
                "discount_percent" => 0,
                "description" => "VALORANT is a character-based 5v5 tactical shooter set on the global stage. Outwit, outplay, and outshine your competition with tactical abilities, precise gunplay, and adaptive teamwork.",
                "company" => "Riot Games",
                "url" => "images/valorant.avif",
                "logo" => "logo/valorant.avif",
                "banner" => "banner/valorant.jpg",
                "release_date" => "2020-06-02",
                "os" => "Windows 7/8",
                "gpu" => "NVIDIA GeForce 8800 GT",
                "cpu" => "Intel Core 2 Duo E4600",
                "ram" => 4,
                "storage" => 8,
                "directx" => 9,
                "downloads" => 2500,
                "rating" => 4.3,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "Warframe",
                "genre_id" => 2,
                "price" => 0,
                "discount_percent" => 0,
                "description" => "Warframe is a cooperative free-to-play third person online action game set in an evolving sci-fi world. Join your friends in player-vs-enemy raids across the solar system and master the power of the Warframes. Stand alone or fight together against enemies that threaten your world.",
                "company" => "Digital Extremes",
                "url" => "images/warframe.avif",
                "logo" => "logo/warframe.avif",
                "banner" => "banner/warframe.jpg",
                "release_date" => "2013-03-25",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce 9800 GT",
                "cpu" => "Intel Core 2 Duo E6400",
                "ram" => 4,
                "storage" => 35,
                "directx" => 10,
                "downloads" => 800,
                "rating" => 4.5,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "Watchdogs",
                "genre_id" => 4,
                "price" => 345000,
                "discount_percent" => 90,
                "description" => "In Watch Dogs, players enter the dangerous world of Aiden Pearce, a new class of antihero whose ability to hack into any connected system could be his most powerful weapon. Whether it’s triggering a 30-car pileup by manipulating traffic-lights to trap an enemy during a downtown shootout or tapping into the city’s omnipresent security cameras to access anyone’s personal information, Pearce is capable of coercing and controlling almost every element of the world around him.",
                "company" => "Ubisoft",
                "url" => "images/watchdogs.avif",
                "logo" => "logo/watchdogs.avif",
                "banner" => "banner/watchdogs.avif",
                "release_date" => "2014-05-27",
                "os" => "Windows Vista SP2 64-bit",
                "gpu" => "NVIDIA GeForce GTX 460",
                "cpu" => "Intel Core 2 Quad Q8400",
                "ram" => 6,
                "storage" => 25,
                "directx" => 12,
                "downloads" => 500,
                "rating" => 4.4,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "Watchdogs 2",
                "genre_id" => 4,
                "price" => 345000,
                "discount_percent" => 60,
                "description" => "Play as Marcus Holloway, a brilliant young hacker living in the birthplace of the tech revolution, the San Francisco Bay Area. Team up with Dedsec, a notorious group of hackers, to execute the biggest hack in history; take down ctOS 2.0, an invasive operating system being used by criminal masterminds to monitor and manipulate citizens on a massive scale.",
                "company" => "Ubisoft",
                "url" => "images/watchdogs2.avif",
                "logo" => "logo/watchdogs2.avif",
                "banner" => "banner/watchdogs2.avif",
                "release_date" => "2016-11-29",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 660",
                "cpu" => "Intel Core i5 2400S",
                "ram" => 6,
                "storage" => 50,
                "directx" => 12,
                "downloads" => 500,
                "rating" => 4.5,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "The Witcher 3: Wild Hunt - Complete Edition",
                "genre_id" => 3,
                "price" => 288000,
                "discount_percent" => 0,
                "description" => "The most awarded game of a generation, now enhanced for the next! Experience The Witcher 3: Wild Hunt and its expansions in this definitive collection, boasting improved visuals and performance, new additional content, Photo Mode, and more!",
                "company" => "CD PROJEKT RED",
                "url" => "images/witcher3.avif",
                "logo" => "logo/witcher3.avif",
                "banner" => "banner/witcher3.jpg",
                "release_date" => "2015-05-19",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 770",
                "cpu" => "Intel Core i5-2500K",
                "ram" => 6,
                "storage" => 70,
                "directx" => 11,
                "downloads" => 1500,
                "rating" => 5,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "Witchfire",
                "genre_id" => 2,
                "price" => 0,
                "discount_percent" => 0,
                "description" => "Armed with strange weapons and forbidden pagan magic, hunt a powerful witch holding the key to your salvation. Witchfire is a dark fantasy roguelite shooter from the creators of Painkiller, Bulletstorm, and The Vanishing of Ethan Carter.",
                "company" => "The Astronauts",
                "url" => "images/witchfire.avif",
                "logo" => "logo/witchfire.avif",
                "banner" => "banner/witchfire.jpg",
                "release_date" => "2023-09-20",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 1060",
                "cpu" => "Intel Core i5-2500K",
                "ram" => 8,
                "storage" => 50,
                "directx" => 12,
                "downloads" => 0,
                "rating" => 0,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" =>  Carbon::now()->format('Y-m-d H:i:s')
            ],
            // [
            //     "name" => "Shadow of the Tomb Raider: Definitive Edition",
            //     "genre_id" => 1,
            //     "price" => 659000,
            //     "discount_percent" => 100,
            //     "description" => "Experience the definitive edition of Shadow of the Tomb Raider with the base game, all seven DLC challenge tombs, as well as all downloadable weapons, outfits, and skills – together totaling over $100 in value!",
            //     "company" => "Eidos-Montréal",
            //     "url" => "images/tombraider.avif",
            //     "release_date" => "2018-09-14",
            //     "os" => "Windows 10",
            //     "gpu" => "NVIDIA GeForce GTX 1060",
            //     "cpu" => "Intel Core i7-4770K",
            //     "ram" => 16,
            //     "storage" => 40,
            //     "directx" => 12,
            //     "downloads" => 400,
            //     "rating" => 4.8,
            //     "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
            //     "updated_at" => Carbon::now()->format('Y-m-d H:i:s')
            // ],
            [
                "name" => "Black Book",
                "genre_id" => 8,
                "price" => 199999,
                "discount_percent" => 100,
                "description" => "A fusion of card-based RPGs and Adventure games, “Black Book” is a haunting tale of a young sorceress, who gave her life to serve the dark forces. Dive into the cold, yet alluring world of Slavic folktales - and uncover the secrets that hide in the darkness.",
                "company" => "Morteshka",
                "url" => "images/blackbook.avif",
                "logo" => "logo/blackbook.avif",
                "banner" => "banner/blackbook.avif",
                "release_date" => "2021-08-10",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 660",
                "cpu" => "Intel Core i5-2300",
                "ram" => 8,
                "storage" => 8,
                "directx" => 12,
                "downloads" => 700,
                "rating" => 4.7,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "The Expanse - A Telltale Series",
                "genre_id" => 4,
                "price" => 276999,
                "discount_percent" => 0,
                "description" => "Experience the exciting universe of The Expanse like never before in Telltale’s latest adventure, The Expanse: A Telltale Series. From scavenging wrecked ships in zero-g to combating pirates, you make the difficult choices in this latest Telltale adventure.",
                "company" => "Deck Nine",
                "url" => "images/expanse.webp",
                "logo" => "logo/expanse.avif",
                "banner" => "banner/expanse.jpg",
                "release_date" => "2023-07-23",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 750Ti 2GB",
                "cpu" => "Intel Core i5-2300",
                "ram" => 6,
                "storage" => 15,
                "directx" => 11,
                "downloads" => 260,
                "rating" => 4.4,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "Metro Exodus",
                "genre_id" => 1,
                "price" => 455411,
                "discount_percent" => 100,
                "description" => "The year is 2036. A quarter-century after nuclear war devastated the earth, a few thousand survivors still cling to existence beneath the ruins of Moscow, in the tunnels of the Metro. They have struggled against the poisoned elements, fought mutated beasts and paranormal horrors, and suffered the flames of civil war. But now, as Artyom, you must flee the Metro and lead a band of Spartan Rangers on an incredible, continent-spanning journey across post-apocalyptic Russia in search of a new life in the East.",
                "company" => "4A Games",
                "url" => "images/metroexodus.avif",
                "logo" => "logo/metroexodus.avif",
                "banner" => "banner/metroexodus.jpg",
                "release_date" => "2019-02-15",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 1070",
                "cpu" => "Intel Core i7-4770K",
                "ram" => 8,
                "storage" => 59,
                "directx" => 12,
                "downloads" => 1000,
                "rating" => 4.2,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "Steep",
                "genre_id" => 10,
                "price" => 359000,
                "discount_percent" => 20,
                "description" => "Ride a massive open world of the Alps and Alaska, where the powder is always fresh and the run never ends. Defy and master the world’s most epic mountains on skis, wingsuit, snowboard, and in paraglide. Go solo or drop in side by side with other players. Record and share the most insane stunts ever captured. Dare your friends to try out your custom lines, then challenge the world to beat your best tricks and relive your most epic wipeouts.",
                "company" => "Ubisoft",
                "url" => "images/steep.avif",
                "logo" => "logo/steep.avif",
                "banner" => "banner/steep.avif",
                "release_date" => "2016-12-02",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 980Ti",
                "cpu" => "Intel Core i7 3770K",
                "ram" => 8,
                "storage" => 25,
                "directx" => 11,
                "downloads" => 100,
                "rating" => 4.7,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "Biomutant",
                "genre_id" => 3,
                "price" => 372000,
                "discount_percent" => 0,
                "description" => "BIOMUTANT® is an open-world, post-apocalyptic Kung-Fu fable RPG, with a unique martial arts styled combat system allowing you to mix melee, shooting and mutant ability action.",
                "company" => "Experiment 101",
                "url" => "images/biomutant.avif",
                "logo" => "logo/biomutant.webp",
                "banner" => "banner/biomutant.jpg",
                "release_date" => "2021-05-25",
                "os" => "Windows 10 64 Bit",
                "gpu" => "NVIDIA GeForce GTX 1660Ti",
                "cpu" => "AMD Ryzen 5 1600",
                "ram" => 8,
                "storage" => 25,
                "directx" => 12,
                "downloads" => 1000,
                "rating" => 4.3,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "Hogwarts Legacy",
                "genre_id" => 3,
                "price" => 799999,
                "discount_percent" => 10,
                "description" => "Experience a new story set at Hogwarts in the 1800s. Your character is a student who holds the key to an ancient secret that threatens to tear the wizarding world apart. Make allies, battle Dark wizards and decide the fate of the wizarding world.",
                "company" => "Avalanche Software",
                "url" => "images/hogwartslegacy.avif",
                "logo" => "logo/hogwartslegacy.avif",
                "banner" => "banner/hogwartslegacy.avif",
                "release_date" => "2023-01-01",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 1060",
                "cpu" => "Intel Core i5-2300",
                "ram" => 16,
                "storage" => 75,
                "directx" => 12,
                "downloads" => 700,
                "rating" => 4.8,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "The Elder Scrolls V: Skyrim Special Edition",
                "genre_id" => 3,
                "price" => 329999,
                "discount_percent" => 0,
                "description" => "Winner of more than 200 Game of the Year Awards, Skyrim Special Edition brings the epic fantasy to life in stunning detail. The Special Edition includes the critically acclaimed game and add-ons with all-new features like remastered art and effects, volumetric god rays, dynamic depth of field, screen-space reflections, and more. Skyrim Special Edition also brings the full power of PC mods to consoles. New quests, environments, characters, dialogue, armor, weapons and more – with Mods, there are no limits to what you can experience.",
                "company" => "Bethesda Game Studios",
                "url" => "images/skyrim.avif",
                "logo" => "logo/skyrim.avif",
                "banner" => "banner/skyrim.jpg",
                "release_date" => "2016-10-28",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 470",
                "cpu" => "Intel Core i5-750",
                "ram" => 8,
                "storage" => 12,
                "directx" => 11,
                "downloads" => 2000,
                "rating" => 4.9,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "A Second Before The War",
                "genre_id" => 7,
                "price" => 41999,
                "discount_percent" => 15,
                "description" => "When humans have ruined themselves, the war has been started by... animals... Lead the penguins country and save the world in this simple decision-making strategy game. How about a little battle?",
                "company" => "Kaunitz Games",
                "url" => "images/a-second-before-the-war.avif",
                "logo" => "logo/a-second-before-the-war.avif",
                "banner" => "banner/a-second-before-the-war.jpg",
                "release_date" => "2023-07-13",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce 7700",
                "cpu" => "Intel Core 2 Duo E4600",
                "ram" => 2,
                "storage" => 2,
                "directx" => 9,
                "downloads" => 100,
                "rating" => 4.1,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "Project Vesperi",
                "genre_id" => 5,
                "price" => 399999,
                "discount_percent" => 0,
                "description" => "When an intruder enters the station, Evelyn must make choices that impact the lives of everyone around her, and ultimately, humanity.",
                "company" => "Last Praetorian Interactive LLC",
                "url" => "images/projectvesperi.avif",
                "logo" => "logo/projectvesperi.avif",
                "banner" => "banner/projectvesperi.jpg",
                "release_date" => "2023-12-25",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 1660",
                "cpu" => "Intel Core i7-7700",
                "ram" => 8,
                "storage" => 64,
                "directx" => 12,
                "downloads" => 0,
                "rating" => 0,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "Split",
                "genre_id" => 7,
                "price" => 0,
                "discount_percent" => 0,
                "description" => "In the future, giant city-states have emerged, separated from each other by indestructible barriers. Most professions have been taken over by machines. People work mainly as mechanics, programmers or operators.",
                "company" => "Garlic Jam",
                "url" => "images/split.avif",
                "logo" => "logo/split.avif",
                "banner" => "banner/split.jpg",
                "release_date" => "2022-07-04",
                "os" => "Windows 10",
                "gpu" => "Nvidia GPU GeForce GTX 660 / AMD GPU Radeon HD 7870",
                "cpu" => "AMD Phenom II X4 955 / Intel Core i5-750",
                "ram" => 4,
                "storage" => 8,
                "directx" => 10,
                "downloads" => 450,
                "rating" => 4.5,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "The Last of Us™ Part I",
                "genre_id" => 1,
                "price" => 879999,
                "discount_percent" => 0,
                "description" => "Winner of over 200 Game of the Year awards, The Last of Us™ has been rebuilt for the PlayStation®4 system. Now featuring full 1080p, higher resolution character models, improved shadows and lighting, in addition to several other gameplay improvements.",
                "company" => "Naughty Dog LLC",
                "url" => "images/tlou.avif",
                "logo" => "logo/tlou.avif",
                "banner" => "banner/tlou.jpg",
                "release_date" => "2023-03-28",
                "os" => "Windows 10",
                "gpu" => "NVIDIA GeForce GTX 1080 Ti",
                "cpu" => "Intel Core i7-4770K",
                "ram" => 8,
                "storage" => 100,
                "directx" => 12,
                "downloads" => 230,
                "rating" => 3.9,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                "name" => "PAYDAY 2",
                "genre_id" => 3,
                "price" => 0,
                "discount_percent" => 0,
                "description" => "PAYDAY 2 is an action-packed, four-player co-op shooter that once again lets gamers don the masks of the original PAYDAY crew - Dallas, Hoxton, Wolf and Chains - as they descend on Washington DC for an epic crime spree.",
                "company" => "OVERKILL - a Starbreeze Studio.",
                "url" => "images/payday2.avif",
                "logo" => "logo/payday2.avif",
                "banner" => "banner/payday2.jpg",
                "release_date" => "2013-08-13",
                "os" => "Windows 7",
                "gpu" => "Nvidia & AMD (512MB VRAM)",
                "cpu" => "Intel Dual Core 2.0 GHz",
                "ram" => 4,
                "storage" => 31,
                "directx" => 9,
                "downloads" => 1000,
                "rating" => 4.5,
                "created_at" => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at" => Carbon::now()->format('Y-m-d H:i:s')
            ]
        ];
        DB::table("games")->insert($data);
    }
}
